# Generated by Django 5.0.6 on 2024-08-11 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='El',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('w_s', models.FloatField()),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('exp_el', models.BooleanField()),
                ('f_e', models.FloatField()),
                ('el', models.FloatField()),
                ('p_el', models.FloatField()),
            ],
            options={
                'db_table': 'el',
            },
        ),
        migrations.CreateModel(
            name='electric_line',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'electric_line',
            },
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('ghi', models.FloatField()),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('exp_pv', models.BooleanField()),
                ('f_e', models.FloatField()),
                ('pv', models.FloatField()),
                ('p_pv', models.FloatField()),
            ],
            options={
                'db_table': 'pv',
            },
        ),
        migrations.CreateModel(
            name='region_maroc',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'region_maroc',
            },
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('join_count', models.IntegerField()),
                ('target_fid', models.IntegerField()),
                ('id', models.IntegerField()),
                ('mois1', models.FloatField()),
                ('mois2', models.FloatField()),
                ('mois3', models.FloatField()),
                ('mois4', models.FloatField()),
                ('mois5', models.FloatField()),
                ('mois6', models.FloatField()),
                ('mois7', models.FloatField()),
                ('mois8', models.FloatField()),
                ('mois9', models.FloatField()),
                ('mois10', models.FloatField()),
                ('mois11', models.FloatField()),
                ('mois12', models.FloatField()),
                ('ghi', models.FloatField()),
                ('dhi', models.FloatField()),
                ('bni', models.FloatField()),
                ('temp_avg', models.FloatField()),
                ('srtm', models.FloatField()),
                ('ws_10m', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'shapefiles',
            },
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'ville',
            },
        ),
        migrations.CreateModel(
            name='waterarea_dakhla',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'waterarea_dakhla',
            },
        ),
        migrations.CreateModel(
            name='waterway_doa',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'waterway_doa',
            },
        ),
    ]
